// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzapnxyfvekcybymbif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsemFwbnh5ZnZla2N5YnltYmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTcxOTAsImV4cCI6MjA2NDk3MzE5MH0.HQX1CVBBOHxgh9bWcYybkorHzN1vU9QTPiRkHuIsaEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);